#!/bin/sh
export LD_PRELOAD="/usr/lib/extensions/vulkan/bones/lib/libbones.so${LD_PRELOAD:+:$LD_PRELOAD}"
export VK_ADD_LAYER_PATH="/usr/lib/extensions/vulkan/bones/lib${VK_ADD_LAYER_PATH:+:$VK_ADD_LAYER_PATH}"
export VK_INSTANCE_LAYERS="VK_LAYER_BONES_overlay${VK_INSTANCE_LAYERS:+:$VK_INSTANCE_LAYERS}"
exec "$@"
