#!/bin/sh
BASE="/usr/lib/extensions/vulkan/bones"
export BONES_ENABLE=1
export VK_ADD_LAYER_PATH="${BASE}/share/vulkan/implicit_layer.d${VK_ADD_LAYER_PATH:+:$VK_ADD_LAYER_PATH}"
LIB="${BASE}/lib/x86_64-linux-gnu"
[ -d "${BASE}/lib/i386-linux-gnu" ] && LIB="${LIB}:${BASE}/lib/i386-linux-gnu"
export LD_LIBRARY_PATH="${LIB}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
exec "$@"
