use std::ffi::c_char;
use std::mem;

use crate::interpose::{gl_lookup, reals};

#[derive(Clone, Copy)]
pub(crate) struct GlFns {
    pub(crate) get_error: unsafe extern "C" fn() -> u32,
    pub(crate) get_integerv: unsafe extern "C" fn(u32, *mut i32),
    pub(crate) get_booleanv: unsafe extern "C" fn(u32, *mut u8),
    pub(crate) get_floatv: unsafe extern "C" fn(u32, *mut f32),
    pub(crate) is_enabled: unsafe extern "C" fn(u32) -> u8,
    pub(crate) enable: unsafe extern "C" fn(u32),
    pub(crate) disable: unsafe extern "C" fn(u32),
    pub(crate) viewport: unsafe extern "C" fn(i32, i32, i32, i32),
    pub(crate) scissor: unsafe extern "C" fn(i32, i32, i32, i32),
    pub(crate) color_mask: unsafe extern "C" fn(u8, u8, u8, u8),
    pub(crate) depth_mask: unsafe extern "C" fn(u8),
    pub(crate) stencil_mask: unsafe extern "C" fn(u32),
    pub(crate) clear_color: unsafe extern "C" fn(f32, f32, f32, f32),
    pub(crate) clear: unsafe extern "C" fn(u32),
    pub(crate) pixel_storei: unsafe extern "C" fn(u32, i32),
    pub(crate) blend_func_separate: unsafe extern "C" fn(u32, u32, u32, u32),
    pub(crate) blend_equation_separate: unsafe extern "C" fn(u32, u32),
    pub(crate) active_texture: unsafe extern "C" fn(u32),
    pub(crate) bind_texture: unsafe extern "C" fn(u32, u32),
    pub(crate) gen_textures: unsafe extern "C" fn(i32, *mut u32),
    pub(crate) delete_textures: unsafe extern "C" fn(i32, *const u32),
    pub(crate) tex_image_2d: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, u32, u32, *const std::ffi::c_void),
    pub(crate) tex_parameteri: unsafe extern "C" fn(u32, u32, i32),
    pub(crate) copy_tex_sub_image_2d: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, i32, i32),
    pub(crate) gen_framebuffers: unsafe extern "C" fn(i32, *mut u32),
    pub(crate) delete_framebuffers: unsafe extern "C" fn(i32, *const u32),
    pub(crate) bind_framebuffer: unsafe extern "C" fn(u32, u32),
    pub(crate) framebuffer_texture_2d: unsafe extern "C" fn(u32, u32, u32, u32, i32),
    pub(crate) blit_framebuffer: unsafe extern "C" fn(i32, i32, i32, i32, i32, i32, i32, i32, u32, u32),
    pub(crate) create_shader: unsafe extern "C" fn(u32) -> u32,
    pub(crate) shader_source: unsafe extern "C" fn(u32, i32, *const *const c_char, *const i32),
    pub(crate) compile_shader: unsafe extern "C" fn(u32),
    pub(crate) get_shaderiv: unsafe extern "C" fn(u32, u32, *mut i32),
    pub(crate) create_program: unsafe extern "C" fn() -> u32,
    pub(crate) attach_shader: unsafe extern "C" fn(u32, u32),
    pub(crate) bind_attrib_location: unsafe extern "C" fn(u32, u32, *const c_char),
    pub(crate) link_program: unsafe extern "C" fn(u32),
    pub(crate) get_programiv: unsafe extern "C" fn(u32, u32, *mut i32),
    pub(crate) delete_shader: unsafe extern "C" fn(u32),
    pub(crate) delete_program: unsafe extern "C" fn(u32),
    pub(crate) use_program: unsafe extern "C" fn(u32),
    pub(crate) get_uniform_location: unsafe extern "C" fn(u32, *const c_char) -> i32,
    pub(crate) uniform1i: unsafe extern "C" fn(i32, i32),
    pub(crate) uniform1f: unsafe extern "C" fn(i32, f32),
    pub(crate) uniform2f: unsafe extern "C" fn(i32, f32, f32),
    pub(crate) gen_buffers: unsafe extern "C" fn(i32, *mut u32),
    pub(crate) bind_buffer: unsafe extern "C" fn(u32, u32),
    pub(crate) buffer_data: unsafe extern "C" fn(u32, isize, *const std::ffi::c_void, u32),
    pub(crate) vertex_attrib_pointer: unsafe extern "C" fn(u32, i32, u32, u8, i32, *const std::ffi::c_void),
    pub(crate) enable_vertex_attrib_array: unsafe extern "C" fn(u32),
    pub(crate) disable_vertex_attrib_array: unsafe extern "C" fn(u32),
    pub(crate) get_vertex_attribiv: unsafe extern "C" fn(u32, u32, *mut i32),
    pub(crate) draw_arrays: unsafe extern "C" fn(u32, i32, i32),
    pub(crate) get_string: unsafe extern "C" fn(u32) -> *const c_char,
    pub(crate) gen_vertex_arrays: unsafe extern "C" fn(i32, *mut u32),
    pub(crate) bind_vertex_array: unsafe extern "C" fn(u32),
    pub(crate) delete_buffers: unsafe extern "C" fn(i32, *const u32),
    pub(crate) delete_vertex_arrays: unsafe extern "C" fn(i32, *const u32),
}
pub(crate) fn gl_fns() -> &'static GlFns {
    reals().gl_fns.get_or_init(|| unsafe {
        GlFns {
            get_error: mem::transmute(gl_lookup("glGetError")),
            get_integerv: mem::transmute(gl_lookup("glGetIntegerv")),
            get_booleanv: mem::transmute(gl_lookup("glGetBooleanv")),
            get_floatv: mem::transmute(gl_lookup("glGetFloatv")),
            is_enabled: mem::transmute(gl_lookup("glIsEnabled")),
            enable: mem::transmute(gl_lookup("glEnable")),
            disable: mem::transmute(gl_lookup("glDisable")),
            viewport: mem::transmute(gl_lookup("glViewport")),
            scissor: mem::transmute(gl_lookup("glScissor")),
            color_mask: mem::transmute(gl_lookup("glColorMask")),
            depth_mask: mem::transmute(gl_lookup("glDepthMask")),
            stencil_mask: mem::transmute(gl_lookup("glStencilMask")),
            clear_color: mem::transmute(gl_lookup("glClearColor")),
            clear: mem::transmute(gl_lookup("glClear")),
            pixel_storei: mem::transmute(gl_lookup("glPixelStorei")),
            blend_func_separate: mem::transmute(gl_lookup("glBlendFuncSeparate")),
            blend_equation_separate: mem::transmute(gl_lookup("glBlendEquationSeparate")),
            active_texture: mem::transmute(gl_lookup("glActiveTexture")),
            bind_texture: mem::transmute(gl_lookup("glBindTexture")),
            gen_textures: mem::transmute(gl_lookup("glGenTextures")),
            delete_textures: mem::transmute(gl_lookup("glDeleteTextures")),
            tex_image_2d: mem::transmute(gl_lookup("glTexImage2D")),
            tex_parameteri: mem::transmute(gl_lookup("glTexParameteri")),
            copy_tex_sub_image_2d: mem::transmute(gl_lookup("glCopyTexSubImage2D")),
            gen_framebuffers: mem::transmute(gl_lookup("glGenFramebuffers")),
            delete_framebuffers: mem::transmute(gl_lookup("glDeleteFramebuffers")),
            bind_framebuffer: mem::transmute(gl_lookup("glBindFramebuffer")),
            framebuffer_texture_2d: mem::transmute(gl_lookup("glFramebufferTexture2D")),
            blit_framebuffer: mem::transmute(gl_lookup("glBlitFramebuffer")),
            create_shader: mem::transmute(gl_lookup("glCreateShader")),
            shader_source: mem::transmute(gl_lookup("glShaderSource")),
            compile_shader: mem::transmute(gl_lookup("glCompileShader")),
            get_shaderiv: mem::transmute(gl_lookup("glGetShaderiv")),
            create_program: mem::transmute(gl_lookup("glCreateProgram")),
            attach_shader: mem::transmute(gl_lookup("glAttachShader")),
            bind_attrib_location: mem::transmute(gl_lookup("glBindAttribLocation")),
            link_program: mem::transmute(gl_lookup("glLinkProgram")),
            get_programiv: mem::transmute(gl_lookup("glGetProgramiv")),
            delete_shader: mem::transmute(gl_lookup("glDeleteShader")),
            delete_program: mem::transmute(gl_lookup("glDeleteProgram")),
            use_program: mem::transmute(gl_lookup("glUseProgram")),
            get_uniform_location: mem::transmute(gl_lookup("glGetUniformLocation")),
            uniform1i: mem::transmute(gl_lookup("glUniform1i")),
            uniform1f: mem::transmute(gl_lookup("glUniform1f")),
            uniform2f: mem::transmute(gl_lookup("glUniform2f")),
            gen_buffers: mem::transmute(gl_lookup("glGenBuffers")),
            bind_buffer: mem::transmute(gl_lookup("glBindBuffer")),
            buffer_data: mem::transmute(gl_lookup("glBufferData")),
            vertex_attrib_pointer: mem::transmute(gl_lookup("glVertexAttribPointer")),
            enable_vertex_attrib_array: mem::transmute(gl_lookup("glEnableVertexAttribArray")),
            disable_vertex_attrib_array: mem::transmute(gl_lookup("glDisableVertexAttribArray")),
            get_vertex_attribiv: mem::transmute(gl_lookup("glGetVertexAttribiv")),
            draw_arrays: mem::transmute(gl_lookup("glDrawArrays")),
            get_string: mem::transmute(gl_lookup("glGetString")),
            gen_vertex_arrays: mem::transmute(gl_lookup("glGenVertexArrays")),
            bind_vertex_array: mem::transmute(gl_lookup("glBindVertexArray")),
            delete_buffers: mem::transmute(gl_lookup("glDeleteBuffers")),
            delete_vertex_arrays: mem::transmute(gl_lookup("glDeleteVertexArrays")),
        }
    })
}
